name: grocery_app
description: A comprehensive e-commerce grocery delivery mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design - Core essentials only
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0 # Stable version
  flutter_svg: ^1.1.6
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  lottie: ^1.4.3

  # State Management
  provider: ^6.0.5
  get: ^4.6.5

  # HTTP & API
  http: 1.4.0
  dio: ^4.0.6

  # Database & Storage
  shared_preferences: ^2.0.20    # Older version for compatibility
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Form & Validation
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17

  # Navigation & Routing
  go_router: ^7.1.1     # Older stable version

  # Image & Media
  image_picker: ^0.8.7+4  # Older version
  photo_view: ^0.14.0

  # Utils
  intl: ^0.18.1
  uuid: ^3.0.7
  url_launcher: ^6.1.7  # Older version

  # Security
  crypto: ^3.0.3

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # OPTIONAL PLUGINS - Uncomment as needed after basic app works
  # MongoDB (for backend integration)
  # mongo_dart: ^0.9.4

  # Location & Maps (Requires NDK 27)
  # geolocator: ^8.2.1
  # geocoding: ^2.0.5

  # Permissions (Requires NDK 27)
  # permission_handler: ^9.2.0

  # Device Info (Requires NDK 27)
  # device_info_plus: ^8.2.2
  # package_info_plus: ^3.1.2

  # Payment Integration (Requires NDK 27)
  # razorpay_flutter: ^1.3.2

  # Firebase (Requires NDK 27)
  # firebase_core: ^2.10.0
  # firebase_messaging: ^14.4.1

  # Connectivity (Requires NDK 27)
  # connectivity_plus: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3  # Reduced version
  hive_generator: ^1.1.3  # Reduced version
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Assets

  # Fonts - Using Google Fonts instead of local assets
  # You can use Google Fonts package to load Inter font
  # Or add the font files to assets/fonts/ directory